//@version=5
indicator("Cumulative Volume Delta Oscillator", shorttitle="CVD Oscillator", overlay=false ,max_bars_back = 5000 , max_labels_count = 500, max_lines_count = 500)
ATR = ta.atr(55)

n = input.int(2, title  ="Divergence Fractal Periods", minval=1 , group = 'Logic Setting')
Period = input.int(21 , 'CVD Period', group = 'Logic Setting')
CumMode = input.string('Periodic','Cumulative Mode', [ 'Periodic' , 'EMA'], group = 'Logic Setting')
UltraData = input.bool( false , '' , inline = 'Data', group = 'Logic Setting')
Market = input.string('Forex', 'Market Ultra Data', options = ['Forex', 'Crypto', 'Stock'], inline = 'Data', group = 'Logic Setting')
Show_Label = input.string('Yes' , 'Show Label' , options = ['Yes' , 'No'], group = 'display Setting')
Show_Hidden = input.bool(true, 'Show Hidden Divergences', group = 'display Setting')

var string aa = '' , var string b = '' , var string c = '' , var string d = '' , var string e = '' , var string f = '' , var string g = '' , var string h = ''
var string i = '' , var string j = '' , var string k = '' , var string l = '' , var string m = '' , var string nn = '' , var string o = '' , var string p = ''
var string q = '' , var string r = '' , var string s = '' , var string t = '' , var string u = '' , var string v = '' , var string w = '' , var string x = ''
var string y = '' , var string z = '' 

switch Market 
    'Forex' =>  aa := 'FX', b := 'OANDA' , c := 'FOREXCOM' , d := 'FX_IDC' , e := 'PEPPERSTONE' , f := 'CAPITALCOM' , g := 'ICMARKETS' , h := 'EIGHTCAP' , i := 'SAXO' , j := 'BLACKBULL' , k := 'VANTAGE' , l := 'FUSIONMARKETS' 
     , m := 'FPMARKETS' , nn := 'GBEBROKERS' , o := 'IBKR' , p := 'ACTIVTRADES' , q := 'EASYMARKETS' , r := 'FXOPEN' , s := 'CITYINDEX' , t := 'AFTERPRIME' , u := 'SKILLING' , v := 'WHSELFINVEST' , w := 'TRADENATION'
     , x := 'THINKMARKETS' , y := 'CFI' , z := 'PHILLIPNOVA'

    'Crypto' =>  aa := 'BITSTAMP', b := 'COINBASE' , c := 'INDEX' , d := 'CRYPTO' , e := 'BINANCE' , f := 'BITFINEX' , g := 'KRAKEN' , h := 'OANDA' , i := 'PEPPERSTONE' , j := 'GEMINI' , k := 'EIGHTCAP' , l := 'ICMARKETS' 
     , m := 'VANTAGE' , nn := 'CAPITALCOM' , o := 'FOREXCOM' , p := 'FX' , q := 'BLACKBULL' , r := 'SAXO' , s := 'FUSIONMARKETS' , t := 'CRYPTOCOM' , u := 'EASYMARKETS' , v := 'OKCOIN' , w := 'FPMARKETS'
     , x := 'AFTERPRIME' , y := 'ACTIVTRADES' , z := 'BTSE'

    'Stock' =>  aa := '-', b := '-' , c := '-' , d := '-' , e := '-' , f := '-' , g := '-' , h := '-' , i := '-' , j := '-' , k := '-' , l := '-' 
     , m := '-' , nn := '-' , o := '-' , p := '-' , q := '-' , r := '-' , s := '-' , t := '-' , u := '-' , v := '-' , w := '-'
     , x := '-' , y := '-' , z := '-'

V = nz(request.security(syminfo.tickerid, timeframe.period , volume, ignore_invalid_symbol = true)) 
Va = nz(request.security(aa + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vb = nz(request.security(b + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vc = nz(request.security(c + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vd = nz(request.security(d + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Ve = nz(request.security(e + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vf = nz(request.security(f + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vg = nz(request.security(g + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vh = nz(request.security(h + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vi = nz(request.security(i + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vj = nz(request.security(j + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vk = nz(request.security(k + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vl = nz(request.security(l + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vm = nz(request.security(m + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vn = nz(request.security(nn + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vo = nz(request.security(o + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vp = nz(request.security(p + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vq = nz(request.security(q + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vr = nz(request.security(r + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vs = nz(request.security(s + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vt = nz(request.security(t + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vu = nz(request.security(u + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vv = nz(request.security(v + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vw = nz(request.security(w + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vx = nz(request.security(x + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vy = nz(request.security(y + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 
Vz = nz(request.security(z + ":" + syminfo.ticker, timeframe.period , volume, ignore_invalid_symbol = true)) 

Vsum = V + Va + Vb + Vc + Vd + Ve + Vf + Vg + Vh + Vi + Vj + Vk + Vl + Vm + Vn + Vo + Vp + Vq + Vr + Vs + Vt + Vu + Vv + Vw + Vx + Vy + Vz

Volume = if UltraData 
    Vsum
else
    volume

Buying  = Volume * ((close - low) / (high - low))
Selling = Volume * ((high - close) / (high - low))

delta = Buying - Selling

Hist = if CumMode == "Periodic"
    math.sum(delta , Period)
else if CumMode == "EMA"
    ta.ema(delta , Period) 

//Trend/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

EMA = ta.ema(close, 50)
up_trend = close[n] > EMA
down_trend = close[n] < EMA

//Fractal////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// UpFractal
UpPivot = ta.pivothigh(n,n)

// downFractal
downPivot = ta.pivotlow(n,n)
upFractal = UpPivot and up_trend 
downFractal = downPivot and down_trend 

//Data//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// Bearish Divergence Data (Regular and Hidden)

//price Data
High_Last_Price = ta.valuewhen(upFractal,high[n],0)
High_Per_Price = ta.valuewhen(upFractal,high[n],1)

//CVD hist Data
High_Last_Hist = ta.valuewhen(upFractal, Hist[n],0)
High_Per_Hist = ta.valuewhen(upFractal, Hist[n],1)

//Bar index Data
High_Last_Bar = ta.valuewhen(upFractal, bar_index[n],0)
High_Per_Bar = ta.valuewhen(upFractal, bar_index[n],1)

// Time Condition Bearish
Time_Condition_Bear = (High_Last_Bar + 30) > bar_index

//Regular Bearish Divergence Detector (Price higher highs, CVD lower highs)
Regular_Bearish_Divergence = if High_Last_Hist > 0 and High_Per_Hist > 0 and Time_Condition_Bear and (High_Last_Bar - High_Per_Bar) < 30
    (High_Last_Price > High_Per_Price) and (High_Last_Hist < High_Per_Hist) 
else 
    false

//Hidden Bearish Divergence Detector (Price lower highs, CVD higher highs)
Hidden_Bearish_Divergence = if Show_Hidden and High_Last_Hist > 0 and High_Per_Hist > 0 and Time_Condition_Bear and (High_Last_Bar - High_Per_Bar) < 30
    (High_Last_Price < High_Per_Price) and (High_Last_Hist > High_Per_Hist) 
else 
    false

//count Regular Bear Divergence
var int CRegBearDive = 0 
if ta.change(High_Last_Price) and Regular_Bearish_Divergence == true
    CRegBearDive := CRegBearDive + 1
else if Regular_Bearish_Divergence == false
    CRegBearDive := 0

//count Hidden Bear Divergence
var int CHidBearDive = 0 
if ta.change(High_Last_Price) and Hidden_Bearish_Divergence == true
    CHidBearDive := CHidBearDive + 1
else if Hidden_Bearish_Divergence == false
    CHidBearDive := 0

//Detect change phase in Bearish Divergence
var bool Bear_Phase = na 
len_back_for_Bear_Phase_check = if not na(High_Last_Bar - High_Per_Bar)
    High_Last_Bar - High_Per_Bar
else 
    1

if ta.change(High_Last_Price) and (Regular_Bearish_Divergence == true or Hidden_Bearish_Divergence == true)
    for i = (n+1) to (n+1) + len_back_for_Bear_Phase_check
        if Hist[i] < 0 
            Bear_Phase := true
else if Regular_Bearish_Divergence == false and Hidden_Bearish_Divergence == false
    Bear_Phase := false

// Bullish Divergence Data (Regular and Hidden)

//price Data
Low_Last_Price = ta.valuewhen(downFractal,low[n],0)
Low_Per_Price = ta.valuewhen(downFractal,low[n],1)

//CVD hist Data
Low_Last_Hist = ta.valuewhen(downFractal, Hist[n],0)
Low_Per_Hist = ta.valuewhen(downFractal, Hist[n],1)

//Bar index Data
Low_Last_Bar = ta.valuewhen(downFractal, bar_index[n],0)
Low_Per_Bar = ta.valuewhen(downFractal, bar_index[n],1)

// Time Condition Bullish
Time_Condition_Bull = (Low_Last_Bar + 30) > bar_index 

//Regular Bullish Divergence Detector (Price lower lows, CVD higher lows)
Regular_Bullish_Divergence = if Low_Last_Hist < 0 and Low_Per_Hist < 0 and Time_Condition_Bull and (Low_Last_Bar - Low_Per_Bar) < 30
    (Low_Last_Price < Low_Per_Price) and (Low_Last_Hist > Low_Per_Hist)
else 
    false

//Hidden Bullish Divergence Detector (Price higher lows, CVD lower lows)
Hidden_Bullish_Divergence = if Show_Hidden and Low_Last_Hist < 0 and Low_Per_Hist < 0 and Time_Condition_Bull and (Low_Last_Bar - Low_Per_Bar) < 30
    (Low_Last_Price > Low_Per_Price) and (Low_Last_Hist < Low_Per_Hist)
else 
    false

//count Regular Bull Divergence
var int CRegBullDive = 0 
if ta.change(Low_Last_Price) and Regular_Bullish_Divergence == true
    CRegBullDive := CRegBullDive + 1
else if Regular_Bullish_Divergence == false
    CRegBullDive := 0

//count Hidden Bull Divergence
var int CHidBullDive = 0 
if ta.change(Low_Last_Price) and Hidden_Bullish_Divergence == true
    CHidBullDive := CHidBullDive + 1
else if Hidden_Bullish_Divergence == false
    CHidBullDive := 0

//Detect and count change phase in Bullish Divergence
var bool Bull_Phase = na 
len_back_for_Bull_Phase_check = if not na(Low_Last_Bar - Low_Per_Bar)
    Low_Last_Bar - Low_Per_Bar
else 
    1

if ta.change(Low_Last_Price) and (Regular_Bullish_Divergence == true or Hidden_Bullish_Divergence == true)
    for i = (n+1) to (n+1) + len_back_for_Bull_Phase_check
        if Hist[i] > 0 
            Bull_Phase := true
else if Regular_Bullish_Divergence == false and Hidden_Bullish_Divergence == false
    Bull_Phase := false

//Score Divergence
text_power_reg_bull = if CRegBullDive == 1
    "Normal Bull Dive"
else if CRegBullDive == 2
    "Good Bull Dive"
else if CRegBullDive >= 3
    "Strong Bull Dive"
else 
    "-"

text_power_hid_bull = if CHidBullDive == 1
    "Normal Hidden Bull"
else if CHidBullDive == 2
    "Good Hidden Bull"
else if CHidBullDive >= 3
    "Strong Hidden Bull"
else 
    "-"

text_power_reg_bear = if CRegBearDive == 1
    "Normal Bear Dive"
else if CRegBearDive == 2
    "Good Bear Dive"
else if CRegBearDive >= 3
    "Strong Bear Dive"
else 
    "-"

text_power_hid_bear = if CHidBearDive == 1
    "Normal Hidden Bear"
else if CHidBearDive == 2
    "Good Hidden Bear"
else if CHidBearDive >= 3
    "Strong Hidden Bear"
else 
    "-"

// plot
//Divergence Line & Label
Drawing()=>
    var line BeLine = na
    var line BuLine = na 
    var line HidBeLine = na
    var line HidBuLine = na
    var label BeLabel = na
    var label BuLabel = na
    var label HidBeLabel = na
    var label HidBuLabel = na
    var line BeLine_OnChart = na
    var line BuLine_OnChart = na 
    var line HidBeLine_OnChart = na
    var line HidBuLine_OnChart = na 
    var label BeLabel_OnChart = na
    var label BuLabel_OnChart = na
    var label HidBeLabel_OnChart = na
    var label HidBuLabel_OnChart = na

    // Regular Bullish Divergence
    if Regular_Bullish_Divergence
        BuLine := line.new(Low_Per_Bar, Low_Per_Hist, Low_Last_Bar, Low_Last_Hist, color = color.rgb(21, 151, 25), width = 2)
        if Show_Label == 'Yes'
            BuLabel := label.new(Low_Last_Bar, Low_Last_Hist, '+RD', color = color.green, textcolor = color.white, size = size.small, style = label.style_label_up)
        BuLine_OnChart := line.new(Low_Per_Bar, low[bar_index - Low_Per_Bar], Low_Last_Bar, low[bar_index - Low_Last_Bar], color = color.rgb(21, 151, 25), width = 2, force_overlay = true)
        if Show_Label == 'Yes'
            BuLabel_OnChart := label.new(Low_Last_Bar, low[bar_index - Low_Last_Bar], '+RD', color = color.green, textcolor = color.white, size = size.small, style = label.style_label_up, force_overlay = true)

    // Regular Bearish Divergence
    if Regular_Bearish_Divergence
        BeLine := line.new(High_Per_Bar, High_Per_Hist, High_Last_Bar, High_Last_Hist, color = color.rgb(212, 44, 44), width = 2)
        if Show_Label == 'Yes'
            BeLabel := label.new(High_Last_Bar, High_Last_Hist, '-RD', color = color.red, textcolor = color.white, size = size.small, style = label.style_label_down)
        BeLine_OnChart := line.new(High_Per_Bar, high[bar_index - High_Per_Bar], High_Last_Bar, high[bar_index - High_Last_Bar], color = color.rgb(212, 44, 44), width = 2, force_overlay = true)
        if Show_Label == 'Yes'
            BeLabel_OnChart := label.new(High_Last_Bar, high[bar_index - High_Last_Bar], '-RD', color = color.red, textcolor = color.white, size = size.small, style = label.style_label_down, force_overlay = true)

    // Hidden Bullish Divergence
    if Hidden_Bullish_Divergence
        HidBuLine := line.new(Low_Per_Bar, Low_Per_Hist, Low_Last_Bar, Low_Last_Hist, color = color.rgb(21, 151, 25), width = 1, style = line.style_dashed)
        if Show_Label == 'Yes'
            HidBuLabel := label.new(Low_Last_Bar, Low_Last_Hist, '+HD', color = color.green, textcolor = color.white, size = size.tiny, style = label.style_label_up)
        HidBuLine_OnChart := line.new(Low_Per_Bar, low[bar_index - Low_Per_Bar], Low_Last_Bar, low[bar_index - Low_Last_Bar], color = color.rgb(21, 151, 25), width = 1, style = line.style_dashed, force_overlay = true)
        if Show_Label == 'Yes'
            HidBuLabel_OnChart := label.new(Low_Last_Bar, low[bar_index - Low_Last_Bar], '+HD', color = color.green, textcolor = color.white, size = size.tiny, style = label.style_label_up, force_overlay = true)

    // Hidden Bearish Divergence
    if Hidden_Bearish_Divergence
        HidBeLine := line.new(High_Per_Bar, High_Per_Hist, High_Last_Bar, High_Last_Hist, color = color.rgb(212, 44, 44), width = 1, style = line.style_dashed)
        if Show_Label == 'Yes'
            HidBeLabel := label.new(High_Last_Bar, High_Last_Hist, '-HD', color = color.red, textcolor = color.white, size = size.tiny, style = label.style_label_down)
        HidBeLine_OnChart := line.new(High_Per_Bar, high[bar_index - High_Per_Bar], High_Last_Bar, high[bar_index - High_Last_Bar], color = color.rgb(212, 44, 44), width = 1, style = line.style_dashed, force_overlay = true)
        if Show_Label == 'Yes'
            HidBeLabel_OnChart := label.new(High_Last_Bar, high[bar_index - High_Last_Bar], '-HD', color = color.red, textcolor = color.white, size = size.tiny, style = label.style_label_down, force_overlay = true)

Hist_Color = if Hist > 0 
    color.rgb(76, 175, 79, 50)
else if Hist < 0
    color.rgb(255, 82, 82, 50)

plot(Hist, 'Show Cumulative Vol Delta', color = Hist_Color, style = plot.style_columns)
Drawing()