//@version=5

indicator('EMAs', overlay=true)

emaFast = ta.ema(close, 34)
emaSlow = ta.ema(close, 55)

trendFast = ta.ema(close, 100)
trendSlow = ta.ema(close, 200)

plot(emaFast, color=color.new(color.red, 0), linewidth=1, title="EMA 34 (Fast)")
plot(emaSlow, color=color.new(color.blue, 0), linewidth=1, title="EMA 55 (Slow)")

fast = plot(emaFast, color=color.new(color.black, 100), linewidth=1, title="EMA 34 (Hidden)")
slow = plot(emaSlow, color=color.new(color.black, 100), linewidth=1, title="EMA 55 (Hidden)")

f = plot(trendFast, color=color.new(color.black, 100), linewidth=1, title="EMA 100 (Trend Fast)")
s = plot(trendSlow, color=color.new(color.black, 100), linewidth=1, title="EMA 200 (Trend Slow)")

fill (f, s, color=trendFast > trendSlow ? color.new(color.green, 93) : color.new(color.red, 93), title="EMA Cloud (100/200)")